#! /bin/bash

#set -ex

if [ "$1" == "" ] || [ "$2" == "" ]; then
	echo "script for changing kernel version number tag in binary LKM (vermagic) and renaming all unresolved symbols";
	echo "";
	echo "usage:";
	echo "	generate a "fixed" LKM from original	-	$0 old_lkm.ko new_lkm.ko";
	echo "	insert "fixed "LKM simply, non-forced	-	insmod new_lkm.ko";
	exit 1;
fi

tmp=./modinfo.tmp
rm -f $tmp

# extract existing .modinfo section as binary and new kernel version modinfo section

# find some sample module
sample_lkm=`find "/lib/modules/\`uname -r\`/kernel/" -name "*.ko" | head -1`

# dump vermagic info for current kernel to temp-file
echo -ne `objdump -s -j .modinfo $sample_lkm | 
	awk 'BEGIN{v=0;} /Contents/ {v=1; next; } { if (v==1) print $0; }' | 
	cut -c7-41 | 
	awk '{ printf($0); }' | 
	sed 's/ //g;s/../\\\\x&/g;'` | 
	tr '\000' '\n' | 
	awk '/^vermagic=/,!/^$/ { print $0;}' | 
	tr '\n' '\000' >> $tmp

#hexdump1 $tmp

# dump vermagic info from fixing LKM
echo -ne `objdump -s -j .modinfo $1 | 
	awk 'BEGIN{v=0;} /Contents/ {v=1; next; } { if (v==1) print $0; }' | 
	cut -c7-41 | 
	awk '{ printf($0); }' | 
	sed 's/ //g;s/../\\\\x&/g;'` | 
	tr '\000' '\n' | 
	awk '/^vermagic=/,!/^$/ { next;} {print $0;}' | 
	tr '\n' '\000' >> $tmp

#build the objcopy command
#depmod=depmod
#$depmod -e $1 $OTHERMODULES 2>&1 | sed 's/depmod://g' | grep -vE "^$1:|Unresolved symbols|^#|:$"
#$depmod -e $1 2>&1 | sed 's/depmod://g' | grep -vE "^$1:|Unresolved symbols|^#"
#objcopy="objcopy"

#fix symbols
#CMD="$CMD --redefine-sym=register_serial=register_lucent"

#replace the modinfo section with the new one
#objcopy="$objcopy --remove-section=.modinfo --add-section=.modinfo=$tmp"
#objcopy="$objcopy $*"

#run the command
#$objcopy

objcopy --add-section=.modinf1=$tmp $1 $2
objcopy --rename-section .modinfo=.modinf2 $2 $2
objcopy --rename-section .modinf1=.modinfo $2 $2
#objcopy --remove-section=.modinf2 $2 $2

#remove the section file
rm -f $tmp
