#! /bin/bash
#set -ex

if [ "$1" == "" ] || [ "$2" == "" ]; then
	echo "script for changing kernel version number tag in binary LKM (vermagic) and renaming all unresolved symbols";
	echo "";
	echo "usage:";
	echo "	generate a "fixed" LKM from original	-	$0 old_lkm.ko new_lkm.ko";
	echo "	insert "fixed "LKM simply, non-forced	-	insmod new_lkm.ko";
	exit 1;
fi

tmp=./modinfo.tmp
rm -f $tmp

# find some sample module
sample_lkm=`find "/lib/modules/\`uname -r\`/kernel/" -name "*.ko" | head -1`

# extract .modinfo section from some existing LKM and save in variable
vermagic=$(echo -ne `objdump -s -j .modinfo $sample_lkm | \
	awk 'BEGIN{v=0;} /Contents/ {v=1; next; } { if (v==1) print $0; }' | \
	cut -c7-41 | \
	awk '{ printf($0); }' | \
	sed 's/ //g;s/../\\\\x&/g;'` | \
	tr '\000' '\n' | \
	awk '/^vermagic=/,!/^$/ { print $0;}')

# dump vermagic info from LKM as binary, replacing vermagic with the current one
echo -ne `objdump -s -j .modinfo $1 |
	awk 'BEGIN{v=0;} /Contents/ {v=1; next; } { if (v==1) print $0; }' |
	cut -c7-41 |
	awk '{ printf($0); }' |
	sed 's/ //g;s/../\\\\x&/g;'` |
	tr '\000' '\n' |
	awk -v vermagic="$vermagic" '/^vermagic=/,!/^$/ { print vermagic; next;} {print $0;}' |
	tr '\n' '\000' > $tmp

#depmod=depmod
#$depmod -e $1 $OTHERMODULES 2>&1 | sed 's/depmod://g' | grep -vE "^$1:|Unresolved symbols|^#|:$"
#$depmod -e $1 2>&1 | sed 's/depmod://g' | grep -vE "^$1:|Unresolved symbols|^#"

#fix undefined symbols
#$objcopy="$objcopy --redefine-sym=register_serial=register_lucent"

#replace the modinfo section with the new one
objcopy --add-section=.modinf1=$tmp $1 $2
objcopy --rename-section .modinfo=.modinf2 $2 $2
objcopy --rename-section .modinf1=.modinfo $2 $2
#objcopy --remove-section=.modinf2 $2 $2

#remove the section file
rm -f $tmp
